---
title: "How does Go work?"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Go relies on two functions `source` which simply says run this code, and `setup_function` which does all the hard work. In the example above a URL shortner has been used to shorten `https://raw.githubusercontent.com/ITSLeeds/go/master/pct.R` into `https://git.io/fj9eC`. This script then runs the `setup_function` which will install and update any packages requested as well as doing some basic system checks.

Go is a work in progress and we will add checks over time to make it more useful and to catch new types of set up problems as we encounter them. Please leave your feedback [here](https://github.com/ITSLeeds/go/issues).

## Is it safe?

You might be worried about running some unknown code from the internet on your computer. All the code in Go is open source and in this repo. If you want to be extra safe simply download the `setup_function` from [here](https://github.com/ITSLeeds/go/blob/master/code/setup_function.R) and run though it yourself. 