---
title: "Installing R and R Studio"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

To get the most out of your ITS couse, we recommend you bring your own laptop. This allows you to take the worked examples you do duing the course with you. These intreuctions will help you setup your laptop so it is ready for the course.

* [Instructions for Windows]()
* [Instructions for Linux]()
* [Instructions for Mac]()

### Hardware

To get the most out of an ITS course, we recoeemdn you bring a modern laptop.

**Recommended Hardware**

* Modern CPU (2010 or later)
* 64 Bit Operating System (Windows/Mac/Linux)
* 4+ GB RAM
* 64 GB+ Hard Disk

**Minimum Hardware**

* 32 Bit Operating System (Windows/Mac/Linux)
* 2 GB RAM

**Note** If you use a 32 Bit version of R the maximum amount of memory that can be used by R is 4 GB.

### What is R?

R is a programming language and free software environment for statistical computing and graphics.  R has many capabilities for analysing data and writing software, but in this context, its ability to produce and analyse spatial data and maps is most relevant.

You can find a lot more information about R at:

* https://www.r-project.org/ 
* https://en.wikipedia.org/wiki/R_(programming_language) 

To get started with R, see An Introduction to R [online](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf) or from within R by running `help.start()`, or introductory tutorials such as DataCamp's [free](https://www.datacamp.com/courses/free-introduction-to-r) Introduction to R course.

### What is an R package?

An R package is a small piece of software that extends the basic capabilities of R. It is a bit like how a new phone can do some things out of the box (make phone calls, send email) but you have to install apps to add extra abilities.




### To Use R
