---
title: "Introduction to R"
output: github_document
---

R is a programming language and free software environment for statistical computing and graphics.  R has many capabilities for analysing data and writing software, but in this context, its ability to produce and analyse spatial data and maps is most relevant.

You can find a lot more information about R at:

* https://www.r-project.org/ 
* https://en.wikipedia.org/wiki/R_(programming_language) 

To get started with R, see An Introduction to R [online](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf) or from within R by running `help.start()`, or introductory tutorials such as DataCamp's [free](https://www.datacamp.com/courses/free-introduction-to-r) Introduction to R course.

### What is an R package?

An R package is a small piece of software that extends the basic capabilities of R. It is a bit like how a new phone can do some things out of the box (make phone calls, send email) but you have to install apps to add extra abilities.

### Learning R

If you have never used R before there are lots of free tutorials to get you started, such as:

* https://www.datacamp.com/courses/free-introduction-to-r
* http://www.r-tutor.com/r-introduction
